# Generated by Django 4.2.30 on 2026-05-06 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_unique_sent_notification_per_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFranchiseFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='newsitem',
            name='canonical_url_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='extraction_confidence',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='importance_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='is_backfill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='published_at_precision',
            field=models.CharField(choices=[('exact', 'Exact'), ('date_only', 'Date only'), ('unknown', 'Unknown')], default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='newsitemfranchise',
            name='confidence_score',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='newsitemfranchise',
            name='matched_alias',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newsitemissue',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsitemissue',
            name='relation_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rawitem',
            name='canonical_url_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='rawitem',
            name='extraction_confidence',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='rawitem',
            name='published_at_precision',
            field=models.CharField(choices=[('exact', 'Exact'), ('date_only', 'Date only'), ('unknown', 'Unknown')], default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='rawitem',
            name='raw_published_at_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rawitem',
            name='rejection_reason',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='source',
            name='average_fetch_duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='last_fetch_duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='newsitem',
            index=models.Index(fields=['canonical_url_hash'], name='news_newsit_canonic_55f9bb_idx'),
        ),
        migrations.AddIndex(
            model_name='newsitem',
            index=models.Index(fields=['extraction_confidence', 'is_archived'], name='news_newsit_extract_19a430_idx'),
        ),
        migrations.AddIndex(
            model_name='rawitem',
            index=models.Index(fields=['canonical_url_hash'], name='news_rawite_canonic_3f1377_idx'),
        ),
        migrations.AddIndex(
            model_name='rawitem',
            index=models.Index(fields=['rejection_reason'], name='news_rawite_rejecti_30d521_idx'),
        ),
        migrations.AddField(
            model_name='userfranchisefavorite',
            name='franchise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to='news.franchise'),
        ),
        migrations.AddField(
            model_name='userfranchisefavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franchise_favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userfranchisefavorite',
            index=models.Index(fields=['user', 'franchise'], name='news_userfr_user_id_cd66c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='userfranchisefavorite',
            constraint=models.UniqueConstraint(fields=('user', 'franchise'), name='unique_user_franchise_favorite'),
        ),
    ]
