# Generated by Django 4.2.30 on 2026-05-06 23:11

from django.db import migrations, models


def normalize_unknown_date_confidence(apps, schema_editor):
    RawItem = apps.get_model("news", "RawItem")
    NewsItem = apps.get_model("news", "NewsItem")
    RawItem.objects.filter(published_at__isnull=True, date_confidence="high").update(date_confidence="medium")
    NewsItem.objects.filter(published_at__isnull=True, date_confidence="high").update(date_confidence="medium")


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_quality_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='review_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='issue',
            name='review_required',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='content_type',
            field=models.CharField(choices=[('news_article', 'News article'), ('official_notice', 'Official notice'), ('rumor', 'Rumor'), ('review', 'Review'), ('guide', 'Guide'), ('static_page', 'Static page'), ('list_page', 'List page'), ('hub_page', 'Hub page'), ('roundup', 'Roundup')], db_index=True, default='news_article', max_length=32),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='nintendo_relevance_score',
            field=models.PositiveSmallIntegerField(db_index=True, default=2),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='title_suspect',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='title_suspect_reason',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='newsitemissue',
            name='decision_debug',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='date_confidence',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=16),
        ),
        migrations.AlterField(
            model_name='newsitemissue',
            name='relation',
            field=models.CharField(choices=[('same_story', 'Same story'), ('followup', 'Follow-up'), ('confirmation', 'Confirmation'), ('official_confirmation', 'Official confirmation'), ('debunk', 'Debunk'), ('contradicts', 'Contradicts'), ('source_duplicate', 'Source duplicate'), ('related', 'Related')], default='related', max_length=32),
        ),
        migrations.AlterField(
            model_name='rawitem',
            name='date_confidence',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=16),
        ),
        migrations.RunPython(normalize_unknown_date_confidence, migrations.RunPython.noop),
    ]
