# Generated by Django 4.2.30 on 2026-05-06 23:32

from django.db import migrations


KOREAN_GAME_TYPE_NAMES = {
    "mario": "마리오",
    "zelda": "젤다의 전설",
    "pokemon": "포켓몬",
    "metroid": "메트로이드",
    "animal-crossing": "동물의 숲",
    "splatoon": "스플래툰",
    "kirby": "별의 커비",
    "fire-emblem": "파이어 엠블렘",
    "xenoblade": "제노블레이드",
    "donkey-kong": "동키콩",
    "rhythm-heaven": "리듬 세상",
}

ENGLISH_GAME_TYPE_NAMES = {
    "mario": "Mario",
    "zelda": "Zelda",
    "pokemon": "Pokémon",
    "metroid": "Metroid",
    "animal-crossing": "Animal Crossing",
    "splatoon": "Splatoon",
    "kirby": "Kirby",
    "fire-emblem": "Fire Emblem",
    "xenoblade": "Xenoblade",
    "donkey-kong": "Donkey Kong",
    "rhythm-heaven": "Rhythm Heaven",
}


def forwards(apps, schema_editor):
    Franchise = apps.get_model("news", "Franchise")
    for slug, name in KOREAN_GAME_TYPE_NAMES.items():
        Franchise.objects.filter(slug=slug).update(name=name)


def backwards(apps, schema_editor):
    Franchise = apps.get_model("news", "Franchise")
    for slug, name in ENGLISH_GAME_TYPE_NAMES.items():
        Franchise.objects.filter(slug=slug).update(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_issue_review_reasons_issue_review_required_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='franchise',
            options={'ordering': ['name'], 'verbose_name': '게임종류', 'verbose_name_plural': '게임종류'},
        ),
        migrations.AlterModelOptions(
            name='newsitemfranchise',
            options={'verbose_name': '뉴스 게임종류 연결', 'verbose_name_plural': '뉴스 게임종류 연결'},
        ),
        migrations.AlterModelOptions(
            name='userfranchisefavorite',
            options={'verbose_name': '관심 게임종류', 'verbose_name_plural': '관심 게임종류'},
        ),
        migrations.RunPython(forwards, backwards),
    ]
